language: cpp
compiler: gcc
sudo: required

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:beineri/opt-qt551 -y
- sudo apt-get update

install:
- echo "Installing Qt and GCC"
- sudo apt-get -y install qt-latest gcc-5 g++-5
- echo "Moving to /tmp"
- cd /tmp
- echo "Installing CMake"
- wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
- tar xf cmake-3.3.2-Linux-x86_64.tar.gz
- export CMAKE_EXECUTABLE=/tmp/cmake-3.3.2-Linux-x86_64/bin/cmake
- rm cmake-3.3.2-Linux-x86_64.tar.gz
- echo "Installing DOtherSide"
- git clone https://github.com/filcuc/DOtherSide.git DOtherSide
- cd DOtherSide && git checkout $TRAVIS_BRANCH && mkdir build && cd build
- export CXX=g++-5
- export CC=gcc-5
- source /opt/qt55/bin/qt55-env.sh
- $CMAKE_EXECUTABLE -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
- make
- sudo make install
- cd /tmp && rm -rf DOtherSide
- echo "Installing dmd"
- wget http://downloads.dlang.org/releases/2.x/2.071.0/dmd_2.071.0-0_amd64.deb
- sudo dpkg -i dmd*.deb
- rm dmd*.deb
- echo "Installing dub"
- wget http://code.dlang.org/files/dub-0.9.24-linux-x86_64.tar.gz
- tar xf dub*.gz
- export DUB_EXECUTABLE=/tmp/dub

script:
- cd $TRAVIS_BUILD_DIR/examples/abstractitemmodel && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/contactapp && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/helloworld && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/simpledata && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/slotsandproperties && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/receivesignals && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/resourcebundling && $DUB_EXECUTABLE build
- cd $TRAVIS_BUILD_DIR/examples/qmlregistertype && $DUB_EXECUTABLE build